name: fluent.syntax

on:
  push:
    branches: [ master ]
    paths:
      - .github/workflows/fluent.syntax.yml
      - 'fluent.syntax/**'
      - '!fluent.syntax/docs/**'
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/fluent.syntax.yml
      - 'fluent.syntax/**'
      - '!fluent.syntax/docs/**'

jobs:
  test:
    name: build & test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and check
      working-directory: ./fluent.syntax
      run: ./gradlew test
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and check
      working-directory: ./fluent.syntax
      run: ./gradlew ktlintCheck
